#ifndef SERVICEGLOBAL_H
#define SERVICEGLOBAL_H

#include <QtCore/QtGlobal>

#ifdef BUILDSYS_SHARED_LIBS
#  ifdef BUILDSYS_SERVICE_SOURCE
#    define BUILDSYS_SERVICE_DECL Q_DECL_EXPORT
#  else
#    define BUILDSYS_SERVICE_DECL Q_DECL_IMPORT
#  endif // BUILDSYS_SERVICE_SOURCE
#endif // BUILDSYS_SHARED_LIBS

#ifndef BUILDSYS_SERVICE_DECL
#  define BUILDSYS_SERVICE_DECL
#endif

#endif // SERVICEGLOBAL_H
