#ifndef UTILITYGLOBAL_H
#define UTILITYGLOBAL_H

#include <QtCore/QtGlobal>

#ifdef BUILDSYS_SHARED_LIBS
#  ifdef BUILDSYS_UTILITY_SOURCE
#    define BUILDSYS_UTILITY_DECL Q_DECL_EXPORT
#  else
#    define BUILDSYS_UTILITY_DECL Q_DECL_IMPORT
#  endif // BUILDSYS_UTILITY_SOURCE
#endif // BUILDSYS_SHARED_LIBS

#ifndef BUILDSYS_UTILITY_DECL
#  define BUILDSYS_UTILITY_DECL
#endif

#endif // UTILITYGLOBAL_H
