FIND_PATH( SMTP_INCLUDE_DIR smtpexports.h )

FIND_LIBRARY( SMTP_LIBRARIES NAMES SMTP )

IF( SMTP_LIBRARIES )
    SET( SMTP_LIBRARIES ${SMTP_LIBRARIES} )
ENDIF( SMTP_LIBRARIES )

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( SMTP REQUIRED_VARS SMTP_LIBRARIES SMTP_INCLUDE_DIR )

# show the SMTP_INCLUDE_DIR and SMTP_LIBRARIES variables only in the advanced view
MARK_AS_ADVANCED( SMTP_INCLUDE_DIR SMTP_LIBRARIES )