#define YP_RESULT_NORMAL 0
#define YP_RESULT_ARGUMENT_ERROR 1
#define YP_RESULT_SESSIONID_ERROR 2
#define YP_RESULT_TOKEN_ERROR 3
#define YP_RESULT_NAME_PW_ERROR 4
#define YP_RESULT_SERVER_FULL 5
#define YP_RESULT_USER_NOEXIT 6

#define  YP_TYPE_UNKNOW 0
#define  YP_TYPE_SIGNIN 1
#define  YP_TYPE_RESIGNIN 2
#define  YP_TYPE_PLUSH 3
#define  YP_TYPE_SIGNOUT 4
#define  YP_TYPE_MESSAGE 5
#define  YP_TYPE_RETURN 6
#define  YP_TYPE_STATUSNOTIFY 7
#define  YP_TYPE_STATUSREQUEST 8
#define  YP_TYPE_ADDFRIENDS 9
#define  YP_TYPE_DELFRIENDS 10
#define  YP_TYPE_CHKOUT_OFFLINE_MSG 11

#define YP_ACK_PACK_SIZE 24
#define YP_RESULT_PACK_SIZE 28

#define RETRANSMITCOUNT 5
#define RETRANSTIMESTAMP 5